FROM node:14.17
WORKDIR /home
RUN npm install -g @angular/cli@^11.0.0
WORKDIR /home/ng-app
COPY node_modules* package.json* package-lock.json* .
WORKDIR /home
RUN if [ ! -f ng-app/package.json ]; then ng new ng-app; fi
WORKDIR /home/ng-app
RUN if [ ! -d node_modules ]; then npm install; fi
RUN if [ -d .git ]; then rm -r .git; fi
EXPOSE 4200
CMD ["ng", "serve", "--host", "0.0.0.0"]
